base_path: "/workspace/thviet/trungnnv/vlsp-2025"
cache_dir: "${base_path}/src/cache_dir"

db:
  collection_name: "test_chienpham"

embedding: 
  vector_size: 768
  embedding_model: "huyydangg/DEk21_hcmute_embedding"
  embedding_type: "transformer"

chunking:
  max_tokens: 512
  chunk_overlap: 50
  
retrieval:
  limit: 6
  threshold: 0.6

data:
  corpus_path: "${base_path}/src/data/vlsp/legal_corpus.json"
  train_path: "${base_path}/src/data/vlsp/train.json"
  
output:
  result_path: "${base_path}/src/results/baseline_results.json"
